-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		skins = {
			snake_eye_left = "rbxassetid://14034366397",
			snake_eye_right = "rbxassetid://14034362504",
			snake_main = "rbxassetid://14035801225",
		},
		ui = {
			alert_dismiss = "rbxassetid://14402269904",
			backdrop = "rbxassetid://14136965139",
			blur = "rbxassetid://14120516187",
			button_glow_top = "rbxassetid://14367671668",
			circle = "rbxassetid://14120516288",
			map_crosshair = "rbxassetid://14127467312",
			map_cursor = "rbxassetid://14127465927",
			menu_title = "rbxassetid://14120569384",
			nav_flower = "rbxassetid://14183568377",
			nav_flower_alt = "rbxassetid://14183568458",
			nav_heart = "rbxassetid://14183565399",
			nav_heart_alt = "rbxassetid://14183565469",
			nav_home = "rbxassetid://14183565573",
			nav_home_alt = "rbxassetid://14183565737",
			skin_card_gradient = "rbxassetid://14271107508",
			skin_indicator = "rbxassetid://14282707759",
			skin_indicator_locked = "rbxassetid://14282707833",
			tile_stripes = "rbxassetid://14137143166",
			vignette = "rbxassetid://14120516929",
		},
	},
}