-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		blur_100 = "rbxassetid://14001169741",
		blur_150 = "rbxassetid://14001169850",
		blur_50 = "rbxassetid://14001169959",
		blur_75 = "rbxassetid://14001170092",
		circle = "rbxassetid://14001170211",
		scroll_bar_bottom = "rbxassetid://14001170424",
		scroll_bar_mid = "rbxassetid://14001170501",
		scroll_bar_top = "rbxassetid://14001170564",
	},
}