-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		common = {
			backdrop = "rbxassetid://14035264818",
			blur = "rbxassetid://14036268520",
		},
		skins = {
			snake_eye = "rbxassetid://14026306246",
			snake_eye_left = "rbxassetid://14034366397",
			snake_eye_right = "rbxassetid://14034362504",
			snake_main = "rbxassetid://14035801225",
		},
	},
}